version: "3.1"
services:
  db:
    image: postgres:13
    container_name: dam_postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    ports:
      - "5432:5432"
    volumes:
      - ./datos:/var/lib/postgresql/data
  web:
    image: odoo:16.0
    container_name: dam_odoo
    depends_on:
      - db
    ports:
      - "8069:8069"